apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
        - name: sftp
          image: atmoz/sftp
          args: ["user:password:1001"]
          volumeMounts:
            - mountPath: "/mnt"
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: meu-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-service
spec:
  type: NodePort
  selector:
    app: sftp
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022

